services:
  postgres-a2sv:
    image: postgres:16
    container_name: a2sv_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: a2sv_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - a2sv-net

networks:
  a2sv-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local