services:
  postgres-a2sv:
    image: postgres:16
    container_name: a2sv_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: a2sv_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - a2sv-net
  
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    restart: always

networks:
  a2sv-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
    driver: local